# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'GoogleMapIntegrationDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GoogleMapIntegrationDemo
#  pod 'GooglePlaces'
 # pod 'Google-Maps-iOS-Utils'
  pod 'GoogleMaps'
pod 'GooglePlaces'

pod "libjingle_peerconnection"
pod "SocketRocket"
end
